services: 
  mongodb:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mystrongpasswd
    ports:
      - "27017:27017" 
    volumes:
      - vol:/data/db
  
volumes:
  vol:
