services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mystrongpasswd
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports: 
      - "3306:3306"
    restart: always
    volumes:
      - vol:/var/lib/mysql
    
volumes:
  vol:
