services: 
  ollama:
    container_name: ollama
    image: ollama/ollama 
    restart: always
    volumes: 
      - ollama-vol:/root/.ollama

  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    environment:
      -  OLLAMA_BASE_URL=http://ollama:11434
    restart: always 
    volumes: 
      - open-webui-vol:/app/backend/data
    depends_on:
      - ollama

volumes: 
  ollama-vol:
  open-webui-vol: 
  
